// Word pool for the Just One room only — separate from Codenames' WORD_POOL
// (lib/words.ts) since the two games have different word requirements.
export const JUST_ONE_WORDS: string[] = [
  "Volcano",
  "Umbrella",
  "Skateboard",
  "Lighthouse",
  "Compass",
  "Jungle",
  "Marathon",
  "Telescope",
  "Bicycle",
  "Waterfall",
  "Blueprint",
  "Campfire",
  "Glacier",
  "Harbor",
  "Kaleidoscope",
  "Lantern",
  "Meadow",
  "Orchestra",
  "Pyramid",
  "Quicksand",
  "Reindeer",
  "Sundial",
  "Treehouse",
  "Vineyard",
  "Windmill",
  "Anchor",
  "Beehive",
  "Cactus",
  "Dungeon",
  "Eclipse",
];
