export const WORD_POOL: string[] = [
    "A1",
    "A4",
    "Commercial",
    "Green",
    "Blue",
    "Grading",
    "Warehouse",
    "OKRs",
    "CE",
    "Media",
    "Harry Potter",
    "PDP",
    "Siemensstadt",
    "Poznan",
    "Standup",
    "A/B test",
    "Vagrant",
    "3 year warrantee",
    "Refurbished",
    "Trade-in",
    "Tablar lifts",
    "Express shipping",
    "Rudow",
    "iPhone",
    "MacBook",
    "Apple Watch",
    "PS5",
    "Amplitude",
    "HQ",
    "Hackathon",
    "Team event",
    "Philipp Gattner",
    "Daniel",
    "Conflict",
    "CM1",
    "EBITDA",
    "Snowflake",
    "Metric",
    "All Hands",
    "Sustainability",
    "Meeting",
    "Re-uni",
    "AI",
    "TAM",
    "Accessibility",
    "100% battery",
    "Return",
    "Feedback",
    "Pipeline",
    "Bug",
    "Sprint",
    "Coffee",
    "Black Friday",
    "Repair",
    "Cart",
    "Versandbox",
    "Checkout",
    "Campaign",
    "Trust",
    "Agent",
];
